### ISSUE TITLE
GetMap API Typo in README

### ISSUE THREAD

**Issue by Integralist** [peterbourgon/ctxdata#11]
👋 

In the v3 documentation it states there is a `GetAllMap()` method:  
https://pkg.go.dev/github.com/peterbourgon/ctxdata/v3

But sifting through the README examples (specifically the middleware example), it suggests using `GetMap` (which I believe to be a typo when reviewing the change set that [introduced these changes](https://github.com/peterbourgon/ctxdata/pull/8))...

```diff
func logMiddleware(next http.Handler, dst io.Writer) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ctx, d := ctxdata.New(r.Context())
-       defer func() { json.NewEncoder(dst).Encode(d.GetMap()) }()
+       defer func() { json.NewEncoder(dst).Encode(d.GetAllMap()) }()
        next.ServeHTTP(w, r.WithContext(ctx))
    })
}
```

I've grep'ed the codebase and I can't find another instance of `GetMap` so I believe this is simply a typo.

**Comment by peterbourgon** [comment]
Yep, artifact of a previous version.
