### ISSUE TITLE
Avoiding the 'default value' Argument

### ISSUE THREAD

**Issue by Integralist** [peterbourgon/ctxdata#12]
## Problem

When using any of the `*Data` methods I have to provide a default argument for the associated type, but I don't have a default value other than the type's 'zero value'. This makes the code overly verbose/redundant as I'm just specifying whatever the zero value would normally be.

e.g.

```
d.GetString("request_uri", "")
d.GetInt64("duration", 0)
```

## Suggestion

Make the `defaultValue` argument variadic so that the user doesn't have to provide it themselves. Then provide the zero value if no default is given.

**Comment by Integralist** [comment]
Actually implementing as variadic argument might not be ideal as it could be opened up for abuse, or cause confusion to how the functions should be called (i.e. ambiguity due to potentially _multiple_ arguments being provided).

Eurgh. 😒

**Comment by peterbourgon** [comment]
The alternative here would be e.g.

```
func (d *Data) GetString(key string) string
func (d *Data) GetStringDefault(key string, def string) string
```

**Comment by Integralist** [comment]
That makes a lot of sense 👍

**Comment by Integralist** [comment]
I threw together a quick 'draft' change set...

https://github.com/peterbourgon/ctxdata/compare/master...Integralist:integralist/2020_09_16_v4_new_api_for_defaults?expand=1

Is this the sort of thing you were thinking? 

If so, and you want me to, I can look at writing some tests for the API (it looks like you have tests for some of the API, but not all the `*ctxdata.Data` methods).

**Comment by Integralist** [comment]
Went ahead and wrote some tests for the nee 'non-default' API methods (see earlier branch comparison link). In the morning I'll write up more tests for the default cases.

**Comment by peterbourgon** [comment]
Oh! Thank you, but don't spend too much time on this... I think I'm convinced it's a good idea, and I'm planning on doing it myself (if it's not already done) in the short term. Sorry, probably should have said that initially :)

**Comment by Integralist** [comment]
It's fine. I've spent like an hour max on it. Take a look at the change set anyway and let me know if you want to keep what I've done. If so I'll wrap up the other set of tests in the morning. Won't take long, and then I can open a PR proper for it. 

Only reason I'm forging ahead is that I'm using this package at work now and so have a vested interest 🙂

**Comment by peterbourgon** [comment]
Likewise. Actually hit exactly the condition you're talking about within ~8h of your PR submission and was thinking about the same thing.
