### ISSUE TITLE
Example usage as middleware - highlight From() vs New()

### ISSUE THREAD

**Issue by Xeoncross** [peterbourgon/ctxdata#6]
I started using this but found I was getting nothing when I trying to pull context from different handlers. Then I realized I was using `.New()` instead of `.From()` and didn't read the examples close enough. 

Here is an example of my basic flaw: https://play.golang.org/p/NyeM3HU_jf5

You might want to update the README to point out the difference or maybe add a link to https://pkg.go.dev/github.com/peterbourgon/ctxdata for those of us that need more clear instructions.

**Comment by peterbourgon** [comment]
Hopefully that solves it. Let me know if you want something more specific.
